### ISSUE TITLE
Multiple errors when running reassign

### ISSUE THREAD

**Issue by fgvieira** [genomewalker/bam-filter#25]
Running `reassign` with:
```
filterBAM reassign --threads 10 --bam INPUT.bam --iters 0 --min-read-ani 94 --min-read-count 3 --tmp-dir temp/large_temp --out-bam OUTPUT.bam
```

I am getting the error:
```
INFO ::: 2024-04-30 11:10:20 ::: Using filterBAM version: 1.4.5
INFO ::: 2024-04-30 11:10:20 ::: Temporary directory: temp/large_temp/tmp393cz6sn
INFO ::: 2024-04-30 11:10:20 ::: Loading BAM file
INFO ::: 2024-04-30 11:10:20 ::: ::: BAM file looks good.
INFO ::: 2024-04-30 11:10:20 ::: Resolving multi-mapping reads...
INFO ::: 2024-04-30 11:10:20 ::: ::: Loading BAM file
INFO ::: 2024-04-30 11:10:20 ::: ::: Found 4,100 reference sequences
INFO ::: 2024-04-30 11:10:20 ::: ::: Removing references with less than 3 reads...
INFO ::: 2024-04-30 11:10:20 ::: ::: Keeping 1,290 references
INFO ::: 2024-04-30 11:10:20 ::: ::: Creating reference chunks with uniform read amounts...
^MDistributing keys:   0%|                            | 0.00/1.29k [00:00<?, ?k/s]^M                                                                                ^MINFO ::: 2024-04-30 11:10:20 ::: ::: ::: Created 10 chunks
INFO ::: 2024-04-30 11:10:20 ::: ::: Extracting reads from BAM file...
^MChunks processed:   0%|                                  | 0/10 [00:00<?, ?it/s]^MChunks processed:  10%|██▌                       | 1/10 [00:04<00:44,  4.96s/it]^MChunks processed:  20%|█████▏                    | 2/10 [00:05<00:21,  2.64s/it]^MChunks processed:  50%|███████████
██             | 5/10 [00:07<00:05,  1.12s/it]^MChunks processed:  80%|████████████████████▊     | 8/10 [00:08<00:01,  1.49it/s]^MChunks processed:  90%|███████████████████████▍  | 9/10 [00:08<00:00,  1.57it/s]^M                                                                      
          ^MINFO ::: 2024-04-30 11:10:29 ::: ::: Collecting results...
^M  0%|                                                    | 0/10 [00:00<?, ?it/s]^M                                                                                ^MINFO ::: 2024-04-30 11:10:29 ::: ::: ::: Removed 25 references without alignments
INFO ::: 2024-04-30 11:10:29 ::: ::: Indexing references...
INFO ::: 2024-04-30 11:10:29 ::: ::: Indexing reads...
INFO ::: 2024-04-30 11:10:29 ::: ::: Combining data...
^MProcessing batches:   0%|                             | 0/10 [00:00<?, ?batch/s]^M                                                                                ^MINFO ::: 2024-04-30 11:10:29 ::: ::: References: 1,265 | Reads: 40 | Alignments: 4,643
INFO ::: 2024-04-30 11:10:29 ::: ::: Allocating data...
INFO ::: 2024-04-30 11:10:29 ::: ::: Initializing data structures...
INFO ::: 2024-04-30 11:10:29 ::: ::: Reassigning reads until convergence
^MIter 1:   0%|                                          | 0/9 [00:00<?, ? step/s]^M                                                                                ^MINFO ::: 2024-04-30 11:10:29 ::: ::: Iter: 1 - R: 4,597 | U: 33 | NU: 2 | L: 46
^MIter 2:   0%|                                          | 0/9 [00:00<?, ? step/s]^M                                                                                ^MINFO ::: 2024-04-30 11:10:29 ::: ::: Iter: 2 - R: 2 | U: 1 | NU: 35 | L: 44
^MIter 3:   0%|                                          | 0/9 [00:00<?, ? step/s]^M                                                                                ^MINFO ::: 2024-04-30 11:10:29 ::: ::: Iter: 3 - R: 1 | U: 1 | NU: 36 | L: 43
^MIter 4:   0%|                                          | 0/9 [00:00<?, ? step/s]^M                                                                                ^MINFO ::: 2024-04-30 11:10:29 ::: ::: Iter: 4 - R: 0 | U: 0 | NU: 37 | L: 43
INFO ::: 2024-04-30 11:10:29 ::: ::: ::: No more alignments to remove. Stopping.
INFO ::: 2024-04-30 11:10:29 ::: ::: References: 27 | Reads: 40 | Alignments: 43
INFO ::: 2024-04-30 11:10:29 ::: ::: Unique mapping reads: 37 | Multimapping reads: 6
INFO ::: 2024-04-30 11:10:29 ::: ::: Mapping back indices...
INFO ::: 2024-04-30 11:10:29 ::: ::: Calculating reads per subject...
INFO ::: 2024-04-30 11:10:29 ::: ::: Removing references with less than 3...
INFO ::: 2024-04-30 11:10:29 ::: ::: ::: Keeping 3 references
INFO ::: 2024-04-30 11:10:29 ::: ::: Creating filtered set...
INFO ::: 2024-04-30 11:10:29 ::: ::: Writing to BAM file...
INFO ::: 2024-04-30 11:10:29 ::: ::: Creating reference chunks with uniform read amounts...
^MDistributing keys:   0%|                             | 0.00/3.00 [00:00<?, ?k/s]^M                                                                                ^MINFO ::: 2024-04-30 11:10:29 ::: ::: Using 2 processes to write 2 chunk(s)
Process SyncManager-11:
Traceback (most recent call last):
  File "/tmp/cache/conda/f134def09e4caa5a03ee71f41693e009_/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/tmp/cache/conda/f134def09e4caa5a03ee71f41693e009_/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/tmp/cache/conda/f134def09e4caa5a03ee71f41693e009_/lib/python3.9/multiprocessing/managers.py", line 583, in _run_server
    server = cls._Server(registry, address, authkey, serializer)
  File "/tmp/cache/conda/f134def09e4caa5a03ee71f41693e009_/lib/python3.9/multiprocessing/managers.py", line 156, in __init__
    self.listener = Listener(address=address, backlog=16)
  File "/tmp/cache/conda/f134def09e4caa5a03ee71f41693e009_/lib/python3.9/multiprocessing/connection.py", line 448, in __init__
    self._listener = SocketListener(address, family, backlog)
  File "/tmp/cache/conda/f134def09e4caa5a03ee71f41693e009_/lib/python3.9/multiprocessing/connection.py", line 591, in __init__
    self._socket.bind(address)
OSError: AF_UNIX path too long
Traceback (most recent call last):
  File "/tmp/cache/conda/f134def09e4caa5a03ee71f41693e009_/bin/filterBAM", line 8, in <module>
    sys.exit(main())
  File "/tmp/cache/conda/f134def09e4caa5a03ee71f41693e009_/lib/python3.9/site-packages/bam_filter/__main__.py", line 41, in main
    reassign(args)
  File "/tmp/cache/conda/f134def09e4caa5a03ee71f41693e009_/lib/python3.9/site-packages/bam_filter/reassign.py", line 1112, in reassign
    reassign_reads(
  File "/tmp/cache/conda/f134def09e4caa5a03ee71f41693e009_/lib/python3.9/site-packages/bam_filter/reassign.py", line 1063, in reassign_reads
    write_reassigned_bam(
  File "/tmp/cache/conda/f134def09e4caa5a03ee71f41693e009_/lib/python3.9/site-packages/bam_filter/reassign.py", line 314, in write_reassigned_bam
    with Manager() as manager:
  File "/tmp/cache/conda/f134def09e4caa5a03ee71f41693e009_/lib/python3.9/multiprocessing/context.py", line 57, in Manager
    m.start()
  File "/tmp/cache/conda/f134def09e4caa5a03ee71f41693e009_/lib/python3.9/multiprocessing/managers.py", line 558, in start
    self._address = reader.recv()
  File "/tmp/cache/conda/f134def09e4caa5a03ee71f41693e009_/lib/python3.9/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/tmp/cache/conda/f134def09e4caa5a03ee71f41693e009_/lib/python3.9/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/tmp/cache/conda/f134def09e4caa5a03ee71f41693e009_/lib/python3.9/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError
Traceback (most recent call last):
  File "/tmp/cache/conda/f134def09e4caa5a03ee71f41693e009_/lib/python3.9/weakref.py", line 667, in _exitfunc
    f()
  File "/tmp/cache/conda/f134def09e4caa5a03ee71f41693e009_/lib/python3.9/weakref.py", line 591, in __call__
    return info.func(*info.args, **(info.kwargs or {}))
  File "/tmp/cache/conda/f134def09e4caa5a03ee71f41693e009_/lib/python3.9/tempfile.py", line 829, in _cleanup
    cls._rmtree(name)
  File "/tmp/cache/conda/f134def09e4caa5a03ee71f41693e009_/lib/python3.9/tempfile.py", line 825, in _rmtree
    _shutil.rmtree(name, onerror=onerror)
  File "/tmp/cache/conda/f134def09e4caa5a03ee71f41693e009_/lib/python3.9/shutil.py", line 740, in rmtree
    onerror(os.rmdir, path, sys.exc_info())
  File "/tmp/cache/conda/f134def09e4caa5a03ee71f41693e009_/lib/python3.9/shutil.py", line 738, in rmtree
    os.rmdir(path)
OSError: [Errno 39] Directory not empty: 'temp/large_temp/tmp393cz6sn'
```

**Comment by genomewalker** [comment]
Check your bash variable $TMPDIR; it seems to be longer than the 107 characters allowed by your system.

**Comment by fgvieira** [comment]
The temp variable sis 109 characters length, but who sets that limit? OS? Bash? Python?
Because I can create a `$TMPDIR` variable longer than that.
