### ISSUE TITLE
Error when running filter command

### ISSUE THREAD

**Issue by fgvieira** [genomewalker/bam-filter#26]
When running `fitler` with:
```
filterBAM filter --threads 10 --low-memory --disable-sort --bam INPUT.bam --min-read-ani 94 --min-read-count 3 --min-expected-breadth-ratio 0.5 --min-normalized-entropy auto --min-normalized-gini auto --min-breadth 0 --min-avg-read-ani 90 --min-coverage-evenness 0.4 --min-coverage-mean 0 --include-low-detection --tmp-dir temp/large_temp --bam-filtered OUTPUT.bam --stats OUTPUT.stats.tsv.gz --stats-filtered OUTPUT.stats-filtered.tsv.gz --read-length-freqs OUTPUT.read-length-freqs.json --read-hits-count OUTPUT.read-hits-count.tsv.gz --knee-plot OUTPUT.knee-plot.png
```

Sometimes I get the error:
```
INFO ::: 2024-04-30 11:20:23 ::: Using filterBAM version: 1.4.5
INFO ::: 2024-04-30 11:20:23 ::: Temporary directory: temp/large_temp/tmpx53pfpz2
INFO ::: 2024-04-30 11:20:23 ::: Loading BAM file
INFO ::: 2024-04-30 11:20:23 ::: ::: BAM file looks good.
INFO ::: 2024-04-30 11:20:23 ::: Loading BAM file
INFO ::: 2024-04-30 11:20:23 ::: Found 117 reference sequences
INFO ::: 2024-04-30 11:20:23 ::: Removing references with less than 3 reads...
INFO ::: 2024-04-30 11:20:23 ::: Keeping 37 references
INFO ::: 2024-04-30 11:20:23 ::: Low memory mode enabled, writing filtered BAM file to disk
INFO ::: 2024-04-30 11:20:23 ::: ::: Writing temporary filtered BAM file... (be patient)
INFO ::: 2024-04-30 11:20:23 ::: ::: ::: Filtering 37 references sequentially...
^MReferences processed:   0%|                              | 0/37 [00:00<?, ?it/s]^MReferences processed:  19%|████▏                 | 7/37 [00:00<00:00, 60.50it/s]^M                                                                                ^MINFO ::: 2024-04-30 11:20:23 ::: ::: ::: Sorting BAM file...
INFO ::: 2024-04-30 11:20:24 ::: ::: ::: BAM index not found. Indexing...
INFO ::: 2024-04-30 11:20:24 ::: ::: Creating reference chunks with uniform read amounts...
^MDistributing keys:   0%|                             | 0.00/37.0 [00:00<?, ?k/s]^M                                                                                ^MINFO ::: 2024-04-30 11:20:24 ::: ::: Created 10 chunks
INFO ::: 2024-04-30 11:20:24 ::: Processing 10 chunks
^MReferences processed:   0%|                              | 0/10 [00:00<?, ?it/s]^MReferences processed:  20%|████▍                 | 2/10 [00:00<00:00, 18.79it/s]^MReferences processed:  80%|█████████████████▌    | 8/10 [00:00<00:00, 32.24it/s]^M                                                                                ^MINFO ::: 2024-04-30 11:20:25 ::: Reducing results to a single dataframe
INFO ::: 2024-04-30 11:20:25 ::: Calculating read length frequencies...
INFO ::: 2024-04-30 11:20:26 ::: Calculating read hits counts...
INFO ::: 2024-04-30 11:20:26 ::: Writing reference statistics to OUTPUT.stats.tsv.gz
WARNING ::: 2024-04-30 11:20:26 ::: There's only one genome. Using min_norm_gini=0.5 and min_norm_entropy=0.75. Please check the results.
INFO ::: 2024-04-30 11:20:26 ::: Filtering stats...
INFO ::: 2024-04-30 11:20:26 ::: ::: min_read_count >= 3 & min_read_length >= 30 & min_avg_read_ani >= 90.0 & min_expected_breadth_ratio >= 0.5 & min_breadth >= 0.0 & min_coverage_evenness >= 0.4 & min_coeff_var =< inf & min_coverage_mean >= 0.0 & min_norm_entropy >= 0.75 & min_norm_gini <= 0.5
Traceback (most recent call last):
  File "/tmp/cache/conda/f134def09e4caa5a03ee71f41693e009_/lib/python3.9/site-packages/pandas/core/indexes/base.py", line 3805, in get_loc
    return self._engine.get_loc(casted_key)
  File "index.pyx", line 167, in pandas._libs.index.IndexEngine.get_loc
  File "index.pyx", line 175, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index_class_helper.pxi", line 70, in pandas._libs.index.Int64Engine._check_type
KeyError: 'cov_evenness'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/tmp/cache/conda/f134def09e4caa5a03ee71f41693e009_/bin/filterBAM", line 8, in <module>
    sys.exit(main())
  File "/tmp/cache/conda/f134def09e4caa5a03ee71f41693e009_/lib/python3.9/site-packages/bam_filter/__main__.py", line 43, in main
    filter_references(args)
  File "/tmp/cache/conda/f134def09e4caa5a03ee71f41693e009_/lib/python3.9/site-packages/bam_filter/filter.py", line 242, in filter_references
    filter_reference_BAM(
  File "/tmp/cache/conda/f134def09e4caa5a03ee71f41693e009_/lib/python3.9/site-packages/bam_filter/sam_utils.py", line 1091, in filter_reference_BAM
    df["cov_evenness_tmp"] = df["cov_evenness"]
  File "/tmp/cache/conda/f134def09e4caa5a03ee71f41693e009_/lib/python3.9/site-packages/pandas/core/frame.py", line 4102, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/tmp/cache/conda/f134def09e4caa5a03ee71f41693e009_/lib/python3.9/site-packages/pandas/core/indexes/base.py", line 3812, in get_loc
    raise KeyError(key) from err
KeyError: 'cov_evenness'
```

**Comment by fgvieira** [comment]
As extra info, the problem goes away after running the input file through `reassign`.
