### ISSUE TITLE
filter command removes read group information from header

### ISSUE THREAD

**Issue by fgvieira** [genomewalker/bam-filter#29]
The `filter` command seems to remove header info, namely the read groups.

```
Apr 30, 2024 12:00:44 PM com.intel.gkl.NativeLibraryLoader load
INFO: Loading libgkl_compression.so from jar:file:/tmp/cache/conda/648cdf8f2be58c3598499a9678acbd99_/share/picard-3.1.1-0/picard.jar!/com/intel/gkl/native/libgkl_compression.so
[Tue Apr 30 12:00:44 CEST 2024] MarkDuplicates --TAGGING_POLICY All --INPUT INPUT.bam --OUTPUT OUTPUT.bam --METRICS_FILE OUTPUT.metrics.txt --OPTICAL_DUPLICATE_PIXEL_DISTANCE 12000 --TMP_DIR /tmp/tmpcxnowqch --MAX_SEQUENCES_FOR_DISK_READ_ENDS_MAP 50000 --MAX_FILE_HANDLES_FOR_READ_ENDS_MAP 8000 --SORTING_COLLECTION_SIZE_RATIO 0.25 --TAG_DUPLICATE_SET_MEMBERS false --REMOVE_SEQUENCING_DUPLICATES false --CLEAR_DT true --DUPLEX_UMI false --FLOW_MODE false --FLOW_QUALITY_SUM_STRATEGY false --USE_END_IN_UNPAIRED_READS false --USE_UNPAIRED_CLIPPED_END false --UNPAIRED_END_UNCERTAINTY 0 --FLOW_SKIP_FIRST_N_FLOWS 0 --FLOW_Q_IS_KNOWN_END false --FLOW_EFFECTIVE_QUALITY_THRESHOLD 15 --ADD_PG_TAG_TO_READS true --REMOVE_DUPLICATES false --ASSUME_SORTED false --DUPLICATE_SCORING_STRATEGY SUM_OF_BASE_QUALITIES --PROGRAM_RECORD_ID MarkDuplicates --PROGRAM_GROUP_NAME MarkDuplicates --READ_NAME_REGEX <optimized capture of last three ':' separated fields as numeric values> --MAX_OPTICAL_DUPLICATE_SET_SIZE 300000 --VERBOSITY INFO --QUIET false --VALIDATION_STRINGENCY STRICT --COMPRESSION_LEVEL 5 --MAX_RECORDS_IN_RAM 500000 --CREATE_INDEX false --CREATE_MD5_FILE false --help false --version false --showHidden false --USE_JDK_DEFLATER false --USE_JDK_INFLATER false
[Tue Apr 30 12:00:44 CEST 2024] Executing as lnc113@dandycomp06fl.unicph.domain on Linux 4.18.0-513.11.1.el8_9.x86_64 amd64; OpenJDK 64-Bit Server VM 22.0.1-internal-adhoc.conda.src; Deflater: Intel; Inflater: Intel; Provider GCS is available; Picard version: Version:3.1.1
INFO    2024-04-30 12:00:44     MarkDuplicates  Start of doWork freeMemory: 324215984; totalMemory: 335544320; maxMemory: 30064771072
INFO    2024-04-30 12:00:44     MarkDuplicates  Reading input file and constructing read end information.
INFO    2024-04-30 12:00:44     MarkDuplicates  Will retain up to 108930329 data points before spilling to disk.
[Tue Apr 30 12:00:45 CEST 2024] picard.sam.markduplicates.MarkDuplicates done. Elapsed time: 0.02 minutes.
Runtime.totalMemory()=1660944384
To get help, see http://broadinstitute.github.io/picard/index.html#GettingHelp
Exception in thread "main" htsjdk.samtools.SAMFormatException: SAM validation error: ERROR::READ_GROUP_NOT_FOUND:Record 1, Read name A00706:513:HFHMWDSX3:1:2356:10854:29841, RG ID on SAMRecord not found in header: CGG-3-007859-QSB1_LV3003056737_HFHMWDSX3
        at htsjdk.samtools.SAMUtils.processValidationErrors(SAMUtils.java:460)
        at htsjdk.samtools.BAMFileReader$BAMFileIterator.advance(BAMFileReader.java:865)
        at htsjdk.samtools.BAMFileReader$BAMFileIterator.<init>(BAMFileReader.java:836)
        at htsjdk.samtools.BAMFileReader$BAMFileIterator.<init>(BAMFileReader.java:824)
        at htsjdk.samtools.BAMFileReader.getIterator(BAMFileReader.java:527)
        at htsjdk.samtools.SamReader$PrimitiveSamReaderToSamReaderAdapter.iterator(SamReader.java:495)
        at picard.sam.markduplicates.util.AbstractMarkDuplicatesCommandLineProgram.openInputs(AbstractMarkDuplicatesCommandLineProgram.java:262)
        at picard.sam.markduplicates.MarkDuplicates.buildSortedReadEndLists(MarkDuplicates.java:509)
        at picard.sam.markduplicates.MarkDuplicates.doWork(MarkDuplicates.java:270)
        at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:280)
        at picard.cmdline.PicardCommandLine.instanceMain(PicardCommandLine.java:105)
        at picard.cmdline.PicardCommandLine.main(PicardCommandLine.java:115)
```

**Comment by genomewalker** [comment]
Let me know if it works
